### ISSUE TITLE
windows one click installer to setup a node is not working

### ISSUE THREAD

**Issue by Bashi1212** [XinFinOrg/Node-Setup#31]
Hello. 
i am trying to set up a masternode/backupnode on a vps, but the windows oneclick installer starting up but goes to infinity loop. Not showing any thing. dont showing that its is connected.
please check this installer file.
best regards
Bashi

**Comment by AnilChinchawale** [comment]
Hello,

Can you share latest error logs here to review issue.

**Comment by Bashi1212** [comment]
Hello.
I rolled back. 
I am afraid of losing my xdc.
I will read again the setup guide and if i understand then i will try again.
And then will share log here if something gone wrong.

I am not understanding why to give Coinbase address?

Mvh
Basharat Khan
